version: '3.8'

services:
  db:
    image: postgres:latest
    platform: linux/amd64
    container_name: punkte_postgres
    environment:
      POSTGRES_DB: PunkteDatabase
      POSTGRES_USER: PunkteUSer
      POSTGRES_PASSWORD: Tv#Babenhausen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
